-- Add HeroDefinitionTranslations for es-es, fr-fr, de-de, it-it
-- Run date: 2026-01-20

BEGIN;

-- es-es
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'seed', 'es-es', 'Semilla Heroica', 'La semilla de la que crecen todos los héroes. Haz clic para descubrir tu potencial heroico.', 'En tu corazón late una semilla de heroísmo. Haz clic en ella para descubrir tus primeros héroes y comenzar tu viaje heroico.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'alchimalia_hero', 'es-es', 'Héroe Alchimalia', 'La raíz de todos los héroes, la fuente de la transformación.', 'Tu fiel compañero, el comienzo del viaje heroico.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_puppy', 'es-es', 'Cachorro Valiente', 'Un pequeño cachorro lleno de coraje y determinación.', 'Este pequeño cachorro enfrenta los desafíos de frente, inspirando valentía en todos.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_pup_lvl2', 'es-es', 'Perro Guardián', 'Un protector leal con coraje inquebrantable y devoción.', 'El Perro Guardián vigila, defendiendo a los necesitados con determinación valiente.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_pup_lvl3', 'es-es', 'Perro Legendario', 'Un héroe legendario de coraje inigualable y espíritu noble.', 'El Perro Legendario inspira leyendas, encarnando la forma más pura del coraje heroico.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_curious_cat', 'es-es', 'Gato Curioso', 'Un ser curioso que explora cada rincón del mundo.', 'El Gato Curioso te guía a través de misterios y maravillas, despertando tu curiosidad.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_curious_cat_lvl2', 'es-es', 'Gato Explorador', 'Un explorador intrépido impulsado por curiosidad sin fin y asombro.', 'El Gato Explorador se aventura en territorios desconocidos, descubriendo secretos y misterios ocultos.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_curious_cat_lvl3', 'es-es', 'Gato Místico', 'Un ser místico que ve más allá del velo de la realidad.', 'El Gato Místico navega por dimensiones ocultas, revelando verdades que trascienden el entendimiento normal.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_owl', 'es-es', 'Búho Sabio', 'Un observador agudo, lleno de conocimiento y perspicacia.', 'El Búho Sabio vigila el mundo, compartiendo sabiduría y orientación a los buscadores.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_owl_lvl2', 'es-es', 'Búho Erudito', 'Un erudito con conocimiento enciclopédico y profunda perspicacia.', 'El Búho Erudito comparte conocimiento ancestral, iluminando el camino con sabiduría atemporal.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_owl_lvl3', 'es-es', 'Búho Celestial', 'Un ser celestial que ve los patrones del universo.', 'El Búho Celestial contempla el cosmos, comprendiendo las verdades fundamentales de la existencia.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_playful_horse', 'es-es', 'Caballo Juguetón', 'Una criatura alegre que trae creatividad y diversión a donde va.', 'El Caballo Juguetón galopa libremente, inspirando imaginación e ideas lúdicas.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_playful_horse_lvl2', 'es-es', 'Caballo Artístico', 'Un artista que pinta historias con cada movimiento.', 'El Caballo Artístico crea belleza en movimiento, transformando la imaginación en realidad tangible.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_playful_horse_lvl3', 'es-es', 'Caballo Mítico', 'Una criatura mítica que galopa entre mundos.', 'El Caballo Mítico atraviesa dimensiones, llevando sueños y aspiraciones a nuevas realidades.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_cautious_hedgehog', 'es-es', 'Erizo Cauteloso', 'Un protector cuidadoso, atento al peligro y la seguridad.', 'El Erizo enseña prudencia y previsión, manteniendo a todos a salvo.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_cautious_hedgehog_lvl2', 'es-es', 'Erizo Guardián', 'Un guardián protector que crea escudos de seguridad.', 'El Erizo Guardián protege con cuidado, creando espacios seguros para todos.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_cautious_hedgehog_lvl3', 'es-es', 'Erizo Defensor', 'Un defensor formidable con armadura impenetrable.', 'El Erizo Defensor protege con fuerza inquebrantable, siendo el último bastión contra el peligro.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;

-- fr-fr
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'seed', 'fr-fr', 'Graine Héroïque', 'La graine dont naissent tous les héros. Clique pour découvrir ton potentiel héroïque.', 'Dans ton cœur bat une graine d''héroïsme. Clique dessus pour découvrir tes premiers héros et commencer ton voyage héroïque.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'alchimalia_hero', 'fr-fr', 'Héros Alchimalia', 'La racine de tous les héros, la source de la transformation.', 'Ton fidèle compagnon, le début du voyage héroïque.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_puppy', 'fr-fr', 'Chiot Courageux', 'Un petit chiot plein de courage et de détermination.', 'Ce petit chiot affronte les défis de front, inspirant la bravoure chez tous.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_pup_lvl2', 'fr-fr', 'Chien Gardien', 'Un protecteur loyal avec un courage et une dévotion inébranlables.', 'Le Chien Gardien monte la garde, défendant ceux qui ont besoin avec une détermination courageuse.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_pup_lvl3', 'fr-fr', 'Chien Légendaire', 'Un héros légendaire de courage sans égal et d''esprit noble.', 'Le Chien Légendaire inspire des légendes, incarnant la forme la plus pure du courage héroïque.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_curious_cat', 'fr-fr', 'Chat Curieux', 'Un être curieux qui explore chaque recoin du monde.', 'Le Chat Curieux te guide à travers mystères et merveilles, éveillant ta curiosité.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_curious_cat_lvl2', 'fr-fr', 'Chat Explorateur', 'Un explorateur intrépide animé par une curiosité et un émerveillement sans fin.', 'Le Chat Explorateur s''aventure dans des territoires inconnus, découvrant des secrets et des mystères cachés.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_curious_cat_lvl3', 'fr-fr', 'Chat Mystique', 'Un être mystique qui voit au-delà du voile de la réalité.', 'Le Chat Mystique navigue entre dimensions cachées, révélant des vérités qui transcendent la compréhension normale.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_owl', 'fr-fr', 'Hibou Sage', 'Un observateur avisé, plein de savoir et de perspicacité.', 'Le Hibou Sage veille sur le monde, partageant sagesse et conseils aux chercheurs.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_owl_lvl2', 'fr-fr', 'Hibou Érudit', 'Un érudit avec une connaissance encyclopédique et une perspicacité profonde.', 'Le Hibou Érudit partage une connaissance ancestrale, illuminant le chemin avec une sagesse intemporelle.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_owl_lvl3', 'fr-fr', 'Hibou Céleste', 'Un être céleste qui voit les schémas de l''univers.', 'Le Hibou Céleste contemple le cosmos, comprenant les vérités fondamentales de l''existence.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_playful_horse', 'fr-fr', 'Cheval Joueur', 'Une créature joyeuse qui apporte créativité et amusement partout où elle va.', 'Le Cheval Joueur galope librement, inspirant l''imagination et des idées ludiques.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_playful_horse_lvl2', 'fr-fr', 'Cheval Artiste', 'Un artiste qui peint des histoires avec chaque mouvement.', 'Le Cheval Artiste crée de la beauté en mouvement, transformant l''imagination en réalité tangible.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_playful_horse_lvl3', 'fr-fr', 'Cheval Mythique', 'Une créature mythique qui galope entre les mondes.', 'Le Cheval Mythique traverse les dimensions, emportant les rêves et aspirations vers de nouvelles réalités.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_cautious_hedgehog', 'fr-fr', 'Hérisson Prudent', 'Un protecteur attentif, conscient du danger et de la sécurité.', 'Le Hérisson enseigne la prudence et la prévoyance, gardant tout le monde en sécurité.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_cautious_hedgehog_lvl2', 'fr-fr', 'Hérisson Gardien', 'Un gardien protecteur qui crée des boucliers de sécurité.', 'Le Hérisson Gardien protège avec soin, créant des espaces sûrs pour tous.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_cautious_hedgehog_lvl3', 'fr-fr', 'Hérisson Défenseur', 'Un défenseur formidable avec une armure impénétrable.', 'Le Hérisson Défenseur protège avec une force inébranlable, étant le dernier rempart contre le danger.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;

-- Additional hero IDs from hero-tree.json
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_catdog_interstellar', 'es-es', 'GatoPerro Interestelar', 'Un híbrido de curiosidad y coraje, listo para aventuras interestelares.', 'Este híbrido heroico combina los mejores rasgos de gato y perro, explorando el cosmos sin miedo.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_sage', 'es-es', 'Sabio Valiente', 'Una mezcla de sabiduría y valentía, guiando héroes con perspicacia.', 'El Sabio Valiente combina intelecto y coraje para guiar a otros a través de los desafíos.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_artist', 'es-es', 'Artista Valiente', 'Un alma creativa con un corazón valiente.', 'El Artista Valiente pinta relatos heroicos con valentía e imaginación.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_guardian', 'es-es', 'Lobo de Luz', 'Un guardián del coraje, firme contra todas las amenazas.', 'El Lobo de Luz protege el reino, encarnando coraje y vigilancia.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_researcher', 'es-es', 'Investigador Sabio', 'Curioso y analítico, buscando conocimiento en cada rincón.', 'Este héroe descubre secretos y guía a otros con descubrimientos perspicaces.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_creative_explorer', 'es-es', 'Explorador Creativo', 'Un aventurero que combina creatividad con descubrimiento.', 'El Explorador Creativo encuentra caminos nuevos, fusionando imaginación con exploración.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;

INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_catdog_interstellar', 'fr-fr', 'ChatChien Interstellaire', 'Un hybride de curiosité et de courage, prêt pour des aventures interstellaires.', 'Cet hybride héroïque combine les meilleurs traits du chat et du chien, explorant le cosmos sans peur.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_sage', 'fr-fr', 'Sage Courageux', 'Un mélange de sagesse et de bravoure, guidant les héros avec perspicacité.', 'Le Sage Courageux combine intellect et courage pour guider les autres à travers les défis.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_artist', 'fr-fr', 'Artiste Courageux', 'Une âme créative avec un cœur courageux.', 'L''Artiste Courageux peint des récits héroïques avec bravoure et imagination.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_guardian', 'fr-fr', 'Loup de Lumière', 'Un gardien du courage, ferme face à toutes les menaces.', 'Le Loup de Lumière protège le royaume, incarnant courage et vigilance.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_researcher', 'fr-fr', 'Chercheur Sage', 'Curieux et analytique, cherchant le savoir dans chaque recoin.', 'Ce héros découvre des secrets et guide les autres avec des découvertes perspicaces.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_creative_explorer', 'fr-fr', 'Explorateur Créatif', 'Un aventurier qui combine créativité avec découverte.', 'L''Explorateur Créatif trouve de nouveaux chemins, fusionnant imagination avec exploration.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;

-- de-de
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'seed', 'de-de', 'Heldensaat', 'Der Samen, aus dem alle Helden wachsen. Klicke, um dein heldenhaftes Potenzial zu entdecken.', 'In deinem Herz schlägt ein Samen des Heldentums. Klicke darauf, um deine ersten Helden zu entdecken und deine heldenhafte Reise zu beginnen.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'alchimalia_hero', 'de-de', 'Alchimalia Held', 'Die Wurzel aller Helden, die Quelle der Verwandlung.', 'Dein treuer Begleiter, der Beginn der heldenhaften Reise.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_puppy', 'de-de', 'Tapferer Welpe', 'Ein kleiner Welpe voller Mut und Entschlossenheit.', 'Dieser kleine Welpe stellt sich Herausforderungen frontal und inspiriert Tapferkeit bei allen.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_pup_lvl2', 'de-de', 'Wachhund', 'Ein treuer Beschützer mit unerschütterlichem Mut und Hingabe.', 'Der Wachhund hält Wache und verteidigt Bedürftige mit tapferer Entschlossenheit.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_pup_lvl3', 'de-de', 'Legendärer Hund', 'Ein legendärer Held von ungleichem Mut und edlem Geist.', 'Der Legendäre Hund inspiriert Legenden und verkörpert die reinste Form des heldenhaften Mutes.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_curious_cat', 'de-de', 'Neugierige Katze', 'Ein neugieriges Wesen, das jede Ecke der Welt erkundet.', 'Die Neugierige Katze führt dich durch Mysterien und Wunder und erweckt deine Neugier.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_curious_cat_lvl2', 'de-de', 'Entdeckerkatze', 'Ein furchtloser Entdecker angetrieben von endloser Neugier und Staunen.', 'Die Entdeckerkatze wagt sich in unbekannte Gebiete und entdeckt verborgene Geheimnisse und Mysterien.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_curious_cat_lvl3', 'de-de', 'Mystische Katze', 'Ein mystisches Wesen, das jenseits des Schleiers der Realität sieht.', 'Die Mystische Katze navigiert durch verborgene Dimensionen und enthüllt Wahrheiten, die das normale Verständnis transzendieren.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_owl', 'de-de', 'Weiser Uhu', 'Ein scharfer Beobachter, voller Wissen und Einsicht.', 'Der Weise Uhu wacht über die Welt und teilt Weisheit und Anleitung mit Suchenden.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_owl_lvl2', 'de-de', 'Gelehrter Uhu', 'Ein Gelehrter mit enzyklopädischem Wissen und tiefer Einsicht.', 'Der Gelehrte Uhu teilt urzeitliches Wissen und erleuchtet den Weg mit zeitloser Weisheit.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_owl_lvl3', 'de-de', 'Himmlischer Uhu', 'Ein himmlisches Wesen, das die Muster des Universums sieht.', 'Der Himmlische Uhu betrachtet das Kosmos und versteht die fundamentalen Wahrheiten der Existenz.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_playful_horse', 'de-de', 'Verspieltes Pferd', 'Eine fröhliche Kreatur, die Kreativität und Spaß mitbringt, wohin sie auch geht.', 'Das Verspielte Pferd galoppiert frei und inspiriert Vorstellungskraft und spielerische Ideen.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_playful_horse_lvl2', 'de-de', 'Künstlerisches Pferd', 'Ein Künstler, der mit jeder Bewegung Geschichten malt.', 'Das Künstlerische Pferd erschafft Schönheit in Bewegung und verwandelt Fantasie in greifbare Realität.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_playful_horse_lvl3', 'de-de', 'Mythisches Pferd', 'Eine mythische Kreatur, die zwischen Welten galoppiert.', 'Das Mythische Pferd durchquert Dimensionen und trägt Träume und Aspirationen in neue Realitäten.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_cautious_hedgehog', 'de-de', 'Vorsichtiger Igel', 'Ein sorgfältiger Beschützer, achtsam auf Gefahr und Sicherheit.', 'Der Igel lehrt Vorsicht und Voraussicht und hält alle sicher.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_cautious_hedgehog_lvl2', 'de-de', 'Wächter-Igel', 'Ein schützender Wächter, der Sicherheitsschilde erschafft.', 'Der Wächter-Igel schützt sorgfältig und schafft sichere Räume für alle.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_cautious_hedgehog_lvl3', 'de-de', 'Verteidiger-Igel', 'Ein formidabler Verteidiger mit durchdringbarer Rüstung.', 'Der Verteidiger-Igel schützt mit unerschütterlicher Stärke und ist die letzte Bastion gegen Gefahr.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_catdog_interstellar', 'de-de', 'KatzenHund Interstellar', 'Eine Hybride aus Neugier und Mut, bereit für interstellare Abenteuer.', 'Dieser heroische Hybrid kombiniert die besten Eigenschaften von Katze und Hund und erkundet den Kosmos ohne Furcht.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_sage', 'de-de', 'Tapferer Weiser', 'Eine Mischung aus Weisheit und Tapferkeit, die Helden mit Einsicht führt.', 'Der Tapfere Weiser kombiniert Intellekt und Mut, um andere durch Herausforderungen zu führen.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_artist', 'de-de', 'Tapferer Künstler', 'Eine kreative Seele mit einem tapferen Herzen.', 'Der Tapfere Künstler malt heldenhafte Erzählungen mit Mut und Fantasie.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_guardian', 'de-de', 'Wolf des Lichts', 'Ein Wächter des Mutes, fest gegen alle Bedrohungen.', 'Der Wolf des Lichts schützt das Reich und verkörpert Mut und Wachsamkeit.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_researcher', 'de-de', 'Weiser Forscher', 'Neugierig und analytisch, suchend nach Wissen in jeder Ecke.', 'Dieser Held entdeckt Geheimnisse und führt andere mit einsichtsvollen Entdeckungen.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_creative_explorer', 'de-de', 'Kreativer Entdecker', 'Ein Abenteurer, der Kreativität mit Entdeckung kombiniert.', 'Der Kreative Entdecker findet neue Wege und verschmilzt Fantasie mit Erkundung.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;

-- it-it
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'seed', 'it-it', 'Seme Eroico', 'Il seme da cui crescono tutti gli eroi. Clicca per scoprire il tuo potenziale eroico.', 'Nel tuo cuore batte un seme di eroismo. Clicca su di esso per scoprire i tuoi primi eroi e iniziare il tuo viaggio eroico.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'alchimalia_hero', 'it-it', 'Eroe Alchimalia', 'La radice di tutti gli eroi, la fonte della trasformazione.', 'Il tuo fedele compagno, l''inizio del viaggio eroico.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_puppy', 'it-it', 'Cucciolo Coraggioso', 'Un piccolo cucciolo pieno di coraggio e determinazione.', 'Questo piccolo cucciolo affronta le sfide a testa alta, ispirando coraggio in tutti.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_pup_lvl2', 'it-it', 'Cane Guardiano', 'Un protettore leale con coraggio incrollabile e devozione.', 'Il Cane Guardiano veglia, difendendo i bisognosi con determinazione coraggiosa.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_pup_lvl3', 'it-it', 'Cane Leggendario', 'Un eroe leggendario di coraggio senza pari e spirito nobile.', 'Il Cane Leggendario ispira leggende, incarnando la forma più pura del coraggio eroico.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_curious_cat', 'it-it', 'Gatto Curioso', 'Un essere curioso che esplora ogni angolo del mondo.', 'Il Gatto Curioso ti guida attraverso misteri e meraviglie, risvegliando la tua curiosità.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_curious_cat_lvl2', 'it-it', 'Gatto Esploratore', 'Un esploratore audace spinto da curiosità infinita e meraviglia.', 'Il Gatto Esploratore si avventura in territori sconosciuti, scoprendo segreti e misteri nascosti.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_curious_cat_lvl3', 'it-it', 'Gatto Mistico', 'Un essere mistico che vede oltre il velo della realtà.', 'Il Gatto Mistico naviga tra dimensioni nascoste, rivelando verità che trascendono la comprensione normale.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_owl', 'it-it', 'Gufo Saggio', 'Un osservatore acuto, pieno di conoscenza e saggezza.', 'Il Gufo Saggio veglia sul mondo, condividendo saggezza e guida ai cercatori.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_owl_lvl2', 'it-it', 'Gufo Erudito', 'Un erudito con conoscenza enciclopedica e profonda saggezza.', 'Il Gufo Erudito condivide conoscenza antica, illuminando il cammino con saggezza senza tempo.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_owl_lvl3', 'it-it', 'Gufo Celeste', 'Un essere celeste che vede i schemi dell''universo.', 'Il Gufo Celeste contempla il cosmo, comprendendo le verità fondamentali dell''esistenza.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_playful_horse', 'it-it', 'Cavallo Giocoso', 'Una creatura allegra che porta creatività e divertimento ovunque va.', 'Il Cavallo Giocoso galoppa liberamente, ispirando immaginazione e idee ludiche.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_playful_horse_lvl2', 'it-it', 'Cavallo Artista', 'Un artista che dipinge storie con ogni movimento.', 'Il Cavallo Artista crea bellezza in movimento, trasformando l''immaginazione in realtà tangibile.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_playful_horse_lvl3', 'it-it', 'Cavallo Mitico', 'Una creatura mitica che galoppa tra i mondi.', 'Il Cavallo Mitico attraversa dimensioni, portando sogni e aspirazioni a nuove realtà.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_cautious_hedgehog', 'it-it', 'Riccio Cauteloso', 'Un protettore attento, consapevole del pericolo e della sicurezza.', 'Il Riccio insegna prudenza e previdenza, mantenendo tutti al sicuro.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_cautious_hedgehog_lvl2', 'it-it', 'Riccio Guardiano', 'Un guardiano protettore che crea scudi di sicurezza.', 'Il Riccio Guardiano protegge con cura, creando spazi sicuri per tutti.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_cautious_hedgehog_lvl3', 'it-it', 'Riccio Difensore', 'Un difensore formidabile con armatura impenetrabile.', 'Il Riccio Difensore protegge con forza incrollabile, essendo l''ultima bastione contro il pericolo.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_catdog_interstellar', 'it-it', 'GattoCane Interstellare', 'Un ibrido di curiosità e coraggio, pronto per avventure interstellari.', 'Questo ibrido eroico combina i migliori tratti di gatto e cane, esplorando il cosmo senza paura.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_sage', 'it-it', 'Saggio Coraggioso', 'Un misto di saggezza e coraggio, guidando eroi con perspicacia.', 'Il Saggio Coraggioso combina intelletto e coraggio per guidare altri attraverso le sfide.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_artist', 'it-it', 'Artista Coraggioso', 'Un''anima creativa con un cuore coraggioso.', 'L''Artista Coraggioso dipinge racconti eroici con coraggio e immaginazione.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_brave_guardian', 'it-it', 'Lupo di Luce', 'Un guardiano del coraggio, saldo contro ogni minaccia.', 'Il Lupo di Luce protegge il regno, incarnando coraggio e vigilanza.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_wise_researcher', 'it-it', 'Ricercatore Saggio', 'Curioso e analitico, cercando conoscenza in ogni angolo.', 'Questo eroe scopre segreti e guida altri con scoperte perspicaci.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."HeroDefinitionTranslations" ("Id", "HeroDefinitionId", "LanguageCode", "Name", "Description", "Story") VALUES (gen_random_uuid(), 'hero_creative_explorer', 'it-it', 'Esploratore Creativo', 'Un avventuriero che combina creatività con scoperta.', 'L''Esploratore Creativo trova nuovi sentieri, fondendo immaginazione con esplorazione.') ON CONFLICT ("HeroDefinitionId", "LanguageCode") DO NOTHING;

COMMIT;
