-- Add StoryTopicTranslations for es-es, fr-fr, de-de, it-it
-- Run date: 2026-01-20

BEGIN;

-- es-es
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd8933b73-6f53-5fe8-8de8-bfcc099fc8c4', 'es-es', 'Acertijos y adivinanzas') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd85dd066-4b4f-5c3d-b616-0fba92036b59', 'es-es', 'Amistad y trabajo en equipo') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '50e90f6f-1c99-5d9a-8c09-426f45728652', 'es-es', 'Medio ambiente') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'cda808ae-b6f2-5a6a-8107-044ff1a3aac3', 'es-es', 'Final sorpresa') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'e58a4d43-daf3-57e0-af89-035ca7a516c5', 'es-es', 'Pensamiento crítico') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'ac018b49-5115-54f5-aeee-502b4b208ee7', 'es-es', 'Autoaceptación') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '8f357f22-a231-5ba5-8f61-919ac5f2ab51', 'es-es', 'Múltiples hilos narrativos') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '641f7293-8ff2-567c-a7a1-dfa736eb4e62', 'es-es', 'Lento y acogedor') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '515bee87-5213-5c56-83ba-235d9dd6bd54', 'es-es', 'Enfocado en exploración') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'be984289-7651-5629-ab39-ddcf86529f79', 'es-es', 'Alegría y celebración') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '4c92de8f-e004-5040-9727-9fc3bd98a021', 'es-es', 'Diversión misteriosa') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '6156190e-86bc-5840-ae4a-8170b68628ed', 'es-es', 'Perseverancia') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd69a0a3d-c18e-5d41-9bfa-7ab89a07adff', 'es-es', 'Historia popular') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'dad5768a-e954-56ea-a129-5cda781e0253', 'es-es', 'Animales adorables') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'c347c854-cc7e-51ae-840b-ff6edb4e8808', 'es-es', 'Lectura') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '8f9861fc-01b4-5c82-b967-e62f598d0c95', 'es-es', 'Diálogos divertidos') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd2203126-cdfc-5876-8252-84e91eb82d48', 'es-es', 'Final abierto') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '6a69faf5-70c5-5e98-b1fa-8d5338f0ed52', 'es-es', 'Habilidades sociales') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '77eb01d0-18f3-512a-b78e-3cd56579e9f4', 'es-es', 'Matemáticas') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd1bd3908-2385-5c02-ae43-64285112d984', 'es-es', 'Rápido y dinámico') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;

-- fr-fr
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd8933b73-6f53-5fe8-8de8-bfcc099fc8c4', 'fr-fr', 'Puzzles et devinettes') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd85dd066-4b4f-5c3d-b616-0fba92036b59', 'fr-fr', 'Amitié et travail d''équipe') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '50e90f6f-1c99-5d9a-8c09-426f45728652', 'fr-fr', 'Environnement') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'cda808ae-b6f2-5a6a-8107-044ff1a3aac3', 'fr-fr', 'Fin surprenante') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'e58a4d43-daf3-57e0-af89-035ca7a516c5', 'fr-fr', 'Pensée critique') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'ac018b49-5115-54f5-aeee-502b4b208ee7', 'fr-fr', 'Acceptation de soi') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '8f357f22-a231-5ba5-8f61-919ac5f2ab51', 'fr-fr', 'Multiples fils narratifs') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '641f7293-8ff2-567c-a7a1-dfa736eb4e62', 'fr-fr', 'Lent et confortable') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '515bee87-5213-5c56-83ba-235d9dd6bd54', 'fr-fr', 'Axé sur l''exploration') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'be984289-7651-5629-ab39-ddcf86529f79', 'fr-fr', 'Joie et célébration') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '4c92de8f-e004-5040-9727-9fc3bd98a021', 'fr-fr', 'Amusement mystérieux') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '6156190e-86bc-5840-ae4a-8170b68628ed', 'fr-fr', 'Persévérance') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd69a0a3d-c18e-5d41-9bfa-7ab89a07adff', 'fr-fr', 'Histoire populaire') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'dad5768a-e954-56ea-a129-5cda781e0253', 'fr-fr', 'Animaux mignons') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'c347c854-cc7e-51ae-840b-ff6edb4e8808', 'fr-fr', 'Lecture') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '8f9861fc-01b4-5c82-b967-e62f598d0c95', 'fr-fr', 'Dialogues amusants') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd2203126-cdfc-5876-8252-84e91eb82d48', 'fr-fr', 'Fin ouverte') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '6a69faf5-70c5-5e98-b1fa-8d5338f0ed52', 'fr-fr', 'Compétences sociales') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '77eb01d0-18f3-512a-b78e-3cd56579e9f4', 'fr-fr', 'Mathématiques') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd1bd3908-2385-5c02-ae43-64285112d984', 'fr-fr', 'Rapide et dynamique') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;

-- de-de
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd8933b73-6f53-5fe8-8de8-bfcc099fc8c4', 'de-de', 'Rätsel und Knobelspiele') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd85dd066-4b4f-5c3d-b616-0fba92036b59', 'de-de', 'Freundschaft und Teamarbeit') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '50e90f6f-1c99-5d9a-8c09-426f45728652', 'de-de', 'Umwelt') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'cda808ae-b6f2-5a6a-8107-044ff1a3aac3', 'de-de', 'Überraschungsende') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'e58a4d43-daf3-57e0-af89-035ca7a516c5', 'de-de', 'Kritisches Denken') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'ac018b49-5115-54f5-aeee-502b4b208ee7', 'de-de', 'Selbstakzeptanz') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '8f357f22-a231-5ba5-8f61-919ac5f2ab51', 'de-de', 'Mehrere Handlungsstränge') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '641f7293-8ff2-567c-a7a1-dfa736eb4e62', 'de-de', 'Langsam und gemütlich') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '515bee87-5213-5c56-83ba-235d9dd6bd54', 'de-de', 'Explorationsfokussiert') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'be984289-7651-5629-ab39-ddcf86529f79', 'de-de', 'Freude und Feier') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '4c92de8f-e004-5040-9727-9fc3bd98a021', 'de-de', 'Geheimnisvoller Spaß') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '6156190e-86bc-5840-ae4a-8170b68628ed', 'de-de', 'Ausdauer') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd69a0a3d-c18e-5d41-9bfa-7ab89a07adff', 'de-de', 'Populäre Geschichte') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'dad5768a-e954-56ea-a129-5cda781e0253', 'de-de', 'Niedliche Tiere') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'c347c854-cc7e-51ae-840b-ff6edb4e8808', 'de-de', 'Lesen') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '8f9861fc-01b4-5c82-b967-e62f598d0c95', 'de-de', 'Lustige Dialoge') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd2203126-cdfc-5876-8252-84e91eb82d48', 'de-de', 'Offenes Ende') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '6a69faf5-70c5-5e98-b1fa-8d5338f0ed52', 'de-de', 'Soziale Fähigkeiten') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '77eb01d0-18f3-512a-b78e-3cd56579e9f4', 'de-de', 'Mathematik') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd1bd3908-2385-5c02-ae43-64285112d984', 'de-de', 'Schnell und dynamisch') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;

-- it-it
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd8933b73-6f53-5fe8-8de8-bfcc099fc8c4', 'it-it', 'Rompicapi e indovinelli') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd85dd066-4b4f-5c3d-b616-0fba92036b59', 'it-it', 'Amicizia e lavoro di squadra') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '50e90f6f-1c99-5d9a-8c09-426f45728652', 'it-it', 'Ambiente') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'cda808ae-b6f2-5a6a-8107-044ff1a3aac3', 'it-it', 'Finale a sorpresa') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'e58a4d43-daf3-57e0-af89-035ca7a516c5', 'it-it', 'Pensiero critico') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'ac018b49-5115-54f5-aeee-502b4b208ee7', 'it-it', 'Autoaccettazione') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '8f357f22-a231-5ba5-8f61-919ac5f2ab51', 'it-it', 'Multipli fili narrativi') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '641f7293-8ff2-567c-a7a1-dfa736eb4e62', 'it-it', 'Lento e accogliente') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '515bee87-5213-5c56-83ba-235d9dd6bd54', 'it-it', 'Focalizzato sull''esplorazione') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'be984289-7651-5629-ab39-ddcf86529f79', 'it-it', 'Gioia e celebrazione') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '4c92de8f-e004-5040-9727-9fc3bd98a021', 'it-it', 'Divertimento misterioso') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '6156190e-86bc-5840-ae4a-8170b68628ed', 'it-it', 'Perseveranza') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd69a0a3d-c18e-5d41-9bfa-7ab89a07adff', 'it-it', 'Storia popolare') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'dad5768a-e954-56ea-a129-5cda781e0253', 'it-it', 'Animali adorabili') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'c347c854-cc7e-51ae-840b-ff6edb4e8808', 'it-it', 'Lettura') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '8f9861fc-01b4-5c82-b967-e62f598d0c95', 'it-it', 'Dialoghi divertenti') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd2203126-cdfc-5876-8252-84e91eb82d48', 'it-it', 'Finale aperto') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '6a69faf5-70c5-5e98-b1fa-8d5338f0ed52', 'it-it', 'Abilità sociali') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), '77eb01d0-18f3-512a-b78e-3cd56579e9f4', 'it-it', 'Matematica') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryTopicTranslations" ("Id", "StoryTopicId", "LanguageCode", "Label") VALUES (gen_random_uuid(), 'd1bd3908-2385-5c02-ae43-64285112d984', 'it-it', 'Veloce e dinamico') ON CONFLICT ("StoryTopicId", "LanguageCode") DO NOTHING;

COMMIT;
