-- Add StoryAgeGroupTranslations for es-es, fr-fr, de-de, it-it
-- Run date: 2026-01-20

BEGIN;

-- es-es
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), 'a9ed4050-16db-52dd-a49c-5910f7f3bd84', 'es-es', 'Escuela secundaria', 'Historias con conflictos más complejos, humor más sutil, primeros dilemas morales y fantasía científica más rica.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), 'f5b97f49-1f40-569d-bf00-186f8a9b0c32', 'es-es', 'Adolescentes', 'Historias con temas de identidad, moralidad matizada, simbolismo y mayor complejidad narrativa.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), '0ecda95c-08ba-597a-a9d5-6e3b999df4db', 'es-es', 'Escuela primaria', 'Historias con un hilo narrativo claro, personajes memorables, primeros conceptos educativos explícitos.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), '70075176-c3e9-5053-933c-6406b55813bd', 'es-es', 'Preescolar', 'Historias muy simples, muchas imágenes, frases cortas, interactividad física y emociones claras.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;

-- fr-fr
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), 'a9ed4050-16db-52dd-a49c-5910f7f3bd84', 'fr-fr', 'Collège', 'Histoires avec des conflits plus complexes, un humour plus subtil, les premiers dilemmes moraux et une fantasy scientifique plus riche.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), 'f5b97f49-1f40-569d-bf00-186f8a9b0c32', 'fr-fr', 'Adolescents', 'Histoires avec des thèmes d''identité, une moralité nuancée, du symbolisme et une complexité narrative accrue.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), '0ecda95c-08ba-597a-a9d5-6e3b999df4db', 'fr-fr', 'École primaire', 'Histoires avec un fil narratif clair, des personnages mémorables, les premiers concepts éducatifs explicites.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), '70075176-c3e9-5053-933c-6406b55813bd', 'fr-fr', 'Maternelle', 'Histoires très simples, beaucoup d''images, des phrases courtes, une interactivité physique et des émotions claires.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;

-- de-de
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), 'a9ed4050-16db-52dd-a49c-5910f7f3bd84', 'de-de', 'Mittelstufe', 'Geschichten mit komplexeren Konflikten, subtilerem Humor, ersten moralischen Dilemmata und reicherer Science-Fantasy.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), 'f5b97f49-1f40-569d-bf00-186f8a9b0c32', 'de-de', 'Jugendliche', 'Geschichten mit Identitätsthemen, nuancierter Moral, Symbolismus und erhöhter narrativer Komplexität.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), '0ecda95c-08ba-597a-a9d5-6e3b999df4db', 'de-de', 'Grundschule', 'Geschichten mit klarem Handlungsfaden, unvergesslichen Charakteren, ersten expliziten Bildungskonzepten.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), '70075176-c3e9-5053-933c-6406b55813bd', 'de-de', 'Vorschule', 'Sehr einfache Geschichten, viele Bilder, kurze Sätze, physische Interaktivität und klare Emotionen.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;

-- it-it
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), 'a9ed4050-16db-52dd-a49c-5910f7f3bd84', 'it-it', 'Scuola media', 'Storie con conflitti più complessi, umor più sottile, primi dilemmi morali e fantasy scientifica più ricca.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), 'f5b97f49-1f40-569d-bf00-186f8a9b0c32', 'it-it', 'Adolescenti', 'Storie con temi di identità, moralità sfumata, simbolismo e maggiore complessità narrativa.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), '0ecda95c-08ba-597a-a9d5-6e3b999df4db', 'it-it', 'Scuola elementare', 'Storie con un filo narrativo chiaro, personaggi memorabili, primi concetti educativi espliciti.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;
INSERT INTO "alchimalia_schema"."StoryAgeGroupTranslations" ("Id", "StoryAgeGroupId", "LanguageCode", "Label", "Description") VALUES (gen_random_uuid(), '70075176-c3e9-5053-933c-6406b55813bd', 'it-it', 'Scuola materna', 'Storie molto semplici, molte immagini, frasi brevi, interattività fisica ed emozioni chiare.') ON CONFLICT ("StoryAgeGroupId", "LanguageCode") DO NOTHING;

COMMIT;
