-- Adds Story Epic system: tables for creating epics with regions, story nodes, and unlock rules
-- Story Epic allows creators to organize stories in a tree structure similar to Tree of Light

BEGIN;

-- Create StoryEpics table
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpics" (
    "Id" character varying(100) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "OwnerUserId" uuid NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'draft',
    "IsDefault" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_StoryEpics" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpics_AlchimaliaUsers_OwnerUserId" 
        FOREIGN KEY ("OwnerUserId") REFERENCES "alchimalia_schema"."AlchimaliaUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpics_OwnerUserId_Id" 
    ON "alchimalia_schema"."StoryEpics" ("OwnerUserId", "Id");

CREATE INDEX IF NOT EXISTS "IX_StoryEpics_OwnerUserId" 
    ON "alchimalia_schema"."StoryEpics" ("OwnerUserId");

-- Create StoryEpicRegions table
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicRegions" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EpicId" character varying(100) NOT NULL,
    "RegionId" character varying(50) NOT NULL,
    "Label" character varying(100) NOT NULL,
    "ImageUrl" character varying(500),
    "SortOrder" integer NOT NULL DEFAULT 0,
    "IsLocked" boolean NOT NULL DEFAULT false,
    "X" double precision,
    "Y" double precision,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_StoryEpicRegions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicRegions_StoryEpics_EpicId" 
        FOREIGN KEY ("EpicId") REFERENCES "alchimalia_schema"."StoryEpics" ("Id") ON DELETE CASCADE,
    CONSTRAINT "UQ_StoryEpicRegions_EpicId_RegionId" 
        UNIQUE ("EpicId", "RegionId")
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicRegions_EpicId" 
    ON "alchimalia_schema"."StoryEpicRegions" ("EpicId");

CREATE INDEX IF NOT EXISTS "IX_StoryEpicRegions_EpicId_RegionId" 
    ON "alchimalia_schema"."StoryEpicRegions" ("EpicId", "RegionId");

-- Create StoryEpicStoryNodes table
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicStoryNodes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EpicId" character varying(100) NOT NULL,
    "StoryId" character varying(100) NOT NULL,
    "RegionId" character varying(50) NOT NULL,
    "RewardImageUrl" character varying(500),
    "SortOrder" integer NOT NULL DEFAULT 0,
    "X" double precision,
    "Y" double precision,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_StoryEpicStoryNodes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicStoryNodes_StoryEpics_EpicId" 
        FOREIGN KEY ("EpicId") REFERENCES "alchimalia_schema"."StoryEpics" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StoryEpicStoryNodes_StoryEpicRegions_EpicId_RegionId" 
        FOREIGN KEY ("EpicId", "RegionId") REFERENCES "alchimalia_schema"."StoryEpicRegions" ("EpicId", "RegionId") ON DELETE CASCADE,
    CONSTRAINT "UQ_StoryEpicStoryNodes_EpicId_StoryId_RegionId" 
        UNIQUE ("EpicId", "StoryId", "RegionId")
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicStoryNodes_EpicId" 
    ON "alchimalia_schema"."StoryEpicStoryNodes" ("EpicId");

CREATE INDEX IF NOT EXISTS "IX_StoryEpicStoryNodes_EpicId_RegionId" 
    ON "alchimalia_schema"."StoryEpicStoryNodes" ("EpicId", "RegionId");

CREATE INDEX IF NOT EXISTS "IX_StoryEpicStoryNodes_StoryId" 
    ON "alchimalia_schema"."StoryEpicStoryNodes" ("StoryId");

-- Create StoryEpicUnlockRules table
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicUnlockRules" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EpicId" character varying(100) NOT NULL,
    "Type" character varying(20) NOT NULL,
    "FromId" character varying(100) NOT NULL,
    "ToRegionId" character varying(50) NOT NULL,
    "RequiredStoriesCsv" character varying(500),
    "MinCount" integer,
    "StoryId" character varying(100),
    "SortOrder" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_StoryEpicUnlockRules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicUnlockRules_StoryEpics_EpicId" 
        FOREIGN KEY ("EpicId") REFERENCES "alchimalia_schema"."StoryEpics" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicUnlockRules_EpicId" 
    ON "alchimalia_schema"."StoryEpicUnlockRules" ("EpicId");

COMMIT;

