-- Adds Story Epic Craft and Definition tables (similar to StoryCraft and StoryDefinition)
-- StoryEpicCraft = draft epics (for editing)
-- StoryEpicDefinition = published epics (for marketplace)
-- Run date: 2025-12-XX
-- Description: Separates epic drafts from published epics, similar to stories architecture

BEGIN;

-- Create StoryEpicCrafts table (draft epics)
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicCrafts" (
    "Id" character varying(100) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "OwnerUserId" uuid NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'draft',
    "CoverImageUrl" character varying(500),
    "IsDefault" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "BaseVersion" integer NOT NULL DEFAULT 0,
    "LastDraftVersion" integer NOT NULL DEFAULT 0,
    "AssignedReviewerUserId" uuid,
    "ReviewNotes" text,
    "ReviewStartedAt" timestamp with time zone,
    "ReviewEndedAt" timestamp with time zone,
    "ReviewedByUserId" uuid,
    "ApprovedByUserId" uuid,
    CONSTRAINT "PK_StoryEpicCrafts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicCrafts_AlchimaliaUsers_OwnerUserId" 
        FOREIGN KEY ("OwnerUserId") REFERENCES "alchimalia_schema"."AlchimaliaUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StoryEpicCrafts_AlchimaliaUsers_AssignedReviewerUserId" 
        FOREIGN KEY ("AssignedReviewerUserId") REFERENCES "alchimalia_schema"."AlchimaliaUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_StoryEpicCrafts_AlchimaliaUsers_ReviewedByUserId" 
        FOREIGN KEY ("ReviewedByUserId") REFERENCES "alchimalia_schema"."AlchimaliaUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_StoryEpicCrafts_AlchimaliaUsers_ApprovedByUserId" 
        FOREIGN KEY ("ApprovedByUserId") REFERENCES "alchimalia_schema"."AlchimaliaUsers" ("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicCrafts_OwnerUserId_Id" 
    ON "alchimalia_schema"."StoryEpicCrafts" ("OwnerUserId", "Id");
CREATE INDEX IF NOT EXISTS "IX_StoryEpicCrafts_Status" 
    ON "alchimalia_schema"."StoryEpicCrafts" ("Status");
CREATE INDEX IF NOT EXISTS "IX_StoryEpicCrafts_AssignedReviewerUserId" 
    ON "alchimalia_schema"."StoryEpicCrafts" ("AssignedReviewerUserId") 
    WHERE "AssignedReviewerUserId" IS NOT NULL;

-- Create StoryEpicCraftTranslations table
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicCraftTranslations" (
    "Id" uuid NOT NULL,
    "StoryEpicCraftId" character varying(100) NOT NULL,
    "LanguageCode" character varying(10) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000),
    CONSTRAINT "PK_StoryEpicCraftTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicCraftTranslations_StoryEpicCrafts_StoryEpicCraftId" 
        FOREIGN KEY ("StoryEpicCraftId") REFERENCES "alchimalia_schema"."StoryEpicCrafts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "UQ_StoryEpicCraftTranslations_StoryEpicCraftId_LanguageCode" 
        UNIQUE ("StoryEpicCraftId", "LanguageCode")
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicCraftTranslations_StoryEpicCraftId" 
    ON "alchimalia_schema"."StoryEpicCraftTranslations" ("StoryEpicCraftId");

-- Create StoryEpicCraftRegions table
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicCraftRegions" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EpicId" character varying(100) NOT NULL,
    "RegionId" character varying(50) NOT NULL,
    "Label" character varying(100) NOT NULL,
    "ImageUrl" character varying(500),
    "SortOrder" integer NOT NULL DEFAULT 0,
    "IsLocked" boolean NOT NULL DEFAULT false,
    "IsStartupRegion" boolean NOT NULL DEFAULT false,
    "X" double precision,
    "Y" double precision,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_StoryEpicCraftRegions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicCraftRegions_StoryEpicCrafts_EpicId" 
        FOREIGN KEY ("EpicId") REFERENCES "alchimalia_schema"."StoryEpicCrafts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "UQ_StoryEpicCraftRegions_EpicId_RegionId" 
        UNIQUE ("EpicId", "RegionId")
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicCraftRegions_EpicId" 
    ON "alchimalia_schema"."StoryEpicCraftRegions" ("EpicId");
CREATE INDEX IF NOT EXISTS "IX_StoryEpicCraftRegions_EpicId_RegionId" 
    ON "alchimalia_schema"."StoryEpicCraftRegions" ("EpicId", "RegionId");

-- Create StoryEpicCraftStoryNodes table
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicCraftStoryNodes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EpicId" character varying(100) NOT NULL,
    "StoryId" character varying(100) NOT NULL,
    "RegionId" character varying(50) NOT NULL,
    "RewardImageUrl" character varying(500),
    "SortOrder" integer NOT NULL DEFAULT 0,
    "X" double precision,
    "Y" double precision,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_StoryEpicCraftStoryNodes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicCraftStoryNodes_StoryEpicCrafts_EpicId" 
        FOREIGN KEY ("EpicId") REFERENCES "alchimalia_schema"."StoryEpicCrafts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StoryEpicCraftStoryNodes_StoryEpicCraftRegions_EpicId_RegionId" 
        FOREIGN KEY ("EpicId", "RegionId") REFERENCES "alchimalia_schema"."StoryEpicCraftRegions" ("EpicId", "RegionId") ON DELETE CASCADE,
    CONSTRAINT "UQ_StoryEpicCraftStoryNodes_EpicId_StoryId_RegionId" 
        UNIQUE ("EpicId", "StoryId", "RegionId")
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicCraftStoryNodes_EpicId" 
    ON "alchimalia_schema"."StoryEpicCraftStoryNodes" ("EpicId");
CREATE INDEX IF NOT EXISTS "IX_StoryEpicCraftStoryNodes_EpicId_RegionId" 
    ON "alchimalia_schema"."StoryEpicCraftStoryNodes" ("EpicId", "RegionId");
CREATE INDEX IF NOT EXISTS "IX_StoryEpicCraftStoryNodes_StoryId" 
    ON "alchimalia_schema"."StoryEpicCraftStoryNodes" ("StoryId");

-- Create StoryEpicCraftUnlockRules table
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicCraftUnlockRules" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EpicId" character varying(100) NOT NULL,
    "Type" character varying(20) NOT NULL,
    "FromId" character varying(100) NOT NULL,
    "ToRegionId" character varying(50) NOT NULL,
    "RequiredStoriesCsv" character varying(500),
    "MinCount" integer,
    "StoryId" character varying(100),
    "SortOrder" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_StoryEpicCraftUnlockRules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicCraftUnlockRules_StoryEpicCrafts_EpicId" 
        FOREIGN KEY ("EpicId") REFERENCES "alchimalia_schema"."StoryEpicCrafts" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicCraftUnlockRules_EpicId" 
    ON "alchimalia_schema"."StoryEpicCraftUnlockRules" ("EpicId");

-- Create StoryEpicDefinitions table (published epics)
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicDefinitions" (
    "Id" character varying(100) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "OwnerUserId" uuid NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'published',
    "CoverImageUrl" character varying(500),
    "IsDefault" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "PublishedAtUtc" timestamp with time zone,
    "Version" integer NOT NULL DEFAULT 1,
    "BaseVersion" integer NOT NULL DEFAULT 0,
    "LastPublishedVersion" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_StoryEpicDefinitions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicDefinitions_AlchimaliaUsers_OwnerUserId" 
        FOREIGN KEY ("OwnerUserId") REFERENCES "alchimalia_schema"."AlchimaliaUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicDefinitions_OwnerUserId_Id" 
    ON "alchimalia_schema"."StoryEpicDefinitions" ("OwnerUserId", "Id");
CREATE INDEX IF NOT EXISTS "IX_StoryEpicDefinitions_Status" 
    ON "alchimalia_schema"."StoryEpicDefinitions" ("Status");

-- Create StoryEpicDefinitionTranslations table
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicDefinitionTranslations" (
    "Id" uuid NOT NULL,
    "StoryEpicDefinitionId" character varying(100) NOT NULL,
    "LanguageCode" character varying(10) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(1000),
    CONSTRAINT "PK_StoryEpicDefinitionTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicDefinitionTranslations_StoryEpicDefinitions_StoryEpicDefinitionId" 
        FOREIGN KEY ("StoryEpicDefinitionId") REFERENCES "alchimalia_schema"."StoryEpicDefinitions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "UQ_StoryEpicDefinitionTranslations_StoryEpicDefinitionId_LanguageCode" 
        UNIQUE ("StoryEpicDefinitionId", "LanguageCode")
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicDefinitionTranslations_StoryEpicDefinitionId" 
    ON "alchimalia_schema"."StoryEpicDefinitionTranslations" ("StoryEpicDefinitionId");

-- Create StoryEpicDefinitionRegions table
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicDefinitionRegions" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EpicId" character varying(100) NOT NULL,
    "RegionId" character varying(50) NOT NULL,
    "Label" character varying(100) NOT NULL,
    "ImageUrl" character varying(500),
    "SortOrder" integer NOT NULL DEFAULT 0,
    "IsLocked" boolean NOT NULL DEFAULT false,
    "IsStartupRegion" boolean NOT NULL DEFAULT false,
    "X" double precision,
    "Y" double precision,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_StoryEpicDefinitionRegions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicDefinitionRegions_StoryEpicDefinitions_EpicId" 
        FOREIGN KEY ("EpicId") REFERENCES "alchimalia_schema"."StoryEpicDefinitions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "UQ_StoryEpicDefinitionRegions_EpicId_RegionId" 
        UNIQUE ("EpicId", "RegionId")
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicDefinitionRegions_EpicId" 
    ON "alchimalia_schema"."StoryEpicDefinitionRegions" ("EpicId");
CREATE INDEX IF NOT EXISTS "IX_StoryEpicDefinitionRegions_EpicId_RegionId" 
    ON "alchimalia_schema"."StoryEpicDefinitionRegions" ("EpicId", "RegionId");

-- Create StoryEpicDefinitionStoryNodes table
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicDefinitionStoryNodes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EpicId" character varying(100) NOT NULL,
    "StoryId" character varying(100) NOT NULL,
    "RegionId" character varying(50) NOT NULL,
    "RewardImageUrl" character varying(500),
    "SortOrder" integer NOT NULL DEFAULT 0,
    "X" double precision,
    "Y" double precision,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_StoryEpicDefinitionStoryNodes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicDefinitionStoryNodes_StoryEpicDefinitions_EpicId" 
        FOREIGN KEY ("EpicId") REFERENCES "alchimalia_schema"."StoryEpicDefinitions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StoryEpicDefinitionStoryNodes_StoryEpicDefinitionRegions_EpicId_RegionId" 
        FOREIGN KEY ("EpicId", "RegionId") REFERENCES "alchimalia_schema"."StoryEpicDefinitionRegions" ("EpicId", "RegionId") ON DELETE CASCADE,
    CONSTRAINT "UQ_StoryEpicDefinitionStoryNodes_EpicId_StoryId_RegionId" 
        UNIQUE ("EpicId", "StoryId", "RegionId")
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicDefinitionStoryNodes_EpicId" 
    ON "alchimalia_schema"."StoryEpicDefinitionStoryNodes" ("EpicId");
CREATE INDEX IF NOT EXISTS "IX_StoryEpicDefinitionStoryNodes_EpicId_RegionId" 
    ON "alchimalia_schema"."StoryEpicDefinitionStoryNodes" ("EpicId", "RegionId");
CREATE INDEX IF NOT EXISTS "IX_StoryEpicDefinitionStoryNodes_StoryId" 
    ON "alchimalia_schema"."StoryEpicDefinitionStoryNodes" ("StoryId");

-- Create StoryEpicDefinitionUnlockRules table
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicDefinitionUnlockRules" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EpicId" character varying(100) NOT NULL,
    "Type" character varying(20) NOT NULL,
    "FromId" character varying(100) NOT NULL,
    "ToRegionId" character varying(50) NOT NULL,
    "RequiredStoriesCsv" character varying(500),
    "MinCount" integer,
    "StoryId" character varying(100),
    "SortOrder" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_StoryEpicDefinitionUnlockRules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicDefinitionUnlockRules_StoryEpicDefinitions_EpicId" 
        FOREIGN KEY ("EpicId") REFERENCES "alchimalia_schema"."StoryEpicDefinitions" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicDefinitionUnlockRules_EpicId" 
    ON "alchimalia_schema"."StoryEpicDefinitionUnlockRules" ("EpicId");

COMMIT;

