-- Adds independent StoryRegion and EpicHero entities with publish workflow
-- These entities can be reused across multiple epics
-- Similar lifecycle to StoryCraft: draft → in_review → approved → published

BEGIN;

-- Create StoryRegions table (independent regions)
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryRegions" (
    "Id" character varying(100) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "ImageUrl" character varying(500),
    "OwnerUserId" uuid NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'draft',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "PublishedAtUtc" timestamp with time zone,
    "AssignedReviewerUserId" uuid,
    "ReviewNotes" text,
    "ReviewStartedAt" timestamp with time zone,
    "ReviewEndedAt" timestamp with time zone,
    "ReviewedByUserId" uuid,
    "ApprovedByUserId" uuid,
    CONSTRAINT "PK_StoryRegions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryRegions_AlchimaliaUsers_OwnerUserId" 
        FOREIGN KEY ("OwnerUserId") REFERENCES "alchimalia_schema"."AlchimaliaUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StoryRegions_AlchimaliaUsers_AssignedReviewerUserId" 
        FOREIGN KEY ("AssignedReviewerUserId") REFERENCES "alchimalia_schema"."AlchimaliaUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_StoryRegions_AlchimaliaUsers_ReviewedByUserId" 
        FOREIGN KEY ("ReviewedByUserId") REFERENCES "alchimalia_schema"."AlchimaliaUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_StoryRegions_AlchimaliaUsers_ApprovedByUserId" 
        FOREIGN KEY ("ApprovedByUserId") REFERENCES "alchimalia_schema"."AlchimaliaUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "UQ_StoryRegions_OwnerUserId_Id" 
        UNIQUE ("OwnerUserId", "Id")
);

CREATE INDEX IF NOT EXISTS "IX_StoryRegions_OwnerUserId_Id" 
    ON "alchimalia_schema"."StoryRegions" ("OwnerUserId", "Id");

CREATE INDEX IF NOT EXISTS "IX_StoryRegions_OwnerUserId" 
    ON "alchimalia_schema"."StoryRegions" ("OwnerUserId");

CREATE INDEX IF NOT EXISTS "IX_StoryRegions_Status" 
    ON "alchimalia_schema"."StoryRegions" ("Status");

CREATE INDEX IF NOT EXISTS "IX_StoryRegions_AssignedReviewerUserId" 
    ON "alchimalia_schema"."StoryRegions" ("AssignedReviewerUserId");

-- Create EpicHeroes table (independent heroes for epics)
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."EpicHeroes" (
    "Id" character varying(100) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "ImageUrl" character varying(500),
    "GreetingText" text,
    "GreetingAudioUrl" character varying(500),
    "OwnerUserId" uuid NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'draft',
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "PublishedAtUtc" timestamp with time zone,
    "AssignedReviewerUserId" uuid,
    "ReviewNotes" text,
    "ReviewStartedAt" timestamp with time zone,
    "ReviewEndedAt" timestamp with time zone,
    "ReviewedByUserId" uuid,
    "ApprovedByUserId" uuid,
    CONSTRAINT "PK_EpicHeroes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EpicHeroes_AlchimaliaUsers_OwnerUserId" 
        FOREIGN KEY ("OwnerUserId") REFERENCES "alchimalia_schema"."AlchimaliaUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EpicHeroes_AlchimaliaUsers_AssignedReviewerUserId" 
        FOREIGN KEY ("AssignedReviewerUserId") REFERENCES "alchimalia_schema"."AlchimaliaUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_EpicHeroes_AlchimaliaUsers_ReviewedByUserId" 
        FOREIGN KEY ("ReviewedByUserId") REFERENCES "alchimalia_schema"."AlchimaliaUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_EpicHeroes_AlchimaliaUsers_ApprovedByUserId" 
        FOREIGN KEY ("ApprovedByUserId") REFERENCES "alchimalia_schema"."AlchimaliaUsers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "UQ_EpicHeroes_OwnerUserId_Id" 
        UNIQUE ("OwnerUserId", "Id")
);

CREATE INDEX IF NOT EXISTS "IX_EpicHeroes_OwnerUserId_Id" 
    ON "alchimalia_schema"."EpicHeroes" ("OwnerUserId", "Id");

CREATE INDEX IF NOT EXISTS "IX_EpicHeroes_OwnerUserId" 
    ON "alchimalia_schema"."EpicHeroes" ("OwnerUserId");

CREATE INDEX IF NOT EXISTS "IX_EpicHeroes_Status" 
    ON "alchimalia_schema"."EpicHeroes" ("Status");

CREATE INDEX IF NOT EXISTS "IX_EpicHeroes_AssignedReviewerUserId" 
    ON "alchimalia_schema"."EpicHeroes" ("AssignedReviewerUserId");

-- Create StoryEpicRegionReferences table (junction table)
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicRegionReferences" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EpicId" character varying(100) NOT NULL,
    "RegionId" character varying(100) NOT NULL,
    "X" double precision,
    "Y" double precision,
    "SortOrder" integer NOT NULL DEFAULT 0,
    "IsLocked" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_StoryEpicRegionReferences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicRegionReferences_StoryEpicDefinitions_EpicId" 
        FOREIGN KEY ("EpicId") REFERENCES "alchimalia_schema"."StoryEpicDefinitions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StoryEpicRegionReferences_StoryRegions_RegionId" 
        FOREIGN KEY ("RegionId") REFERENCES "alchimalia_schema"."StoryRegions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UQ_StoryEpicRegionReferences_EpicId_RegionId" 
        UNIQUE ("EpicId", "RegionId")
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicRegionReferences_EpicId" 
    ON "alchimalia_schema"."StoryEpicRegionReferences" ("EpicId");

CREATE INDEX IF NOT EXISTS "IX_StoryEpicRegionReferences_EpicId_RegionId" 
    ON "alchimalia_schema"."StoryEpicRegionReferences" ("EpicId", "RegionId");

CREATE INDEX IF NOT EXISTS "IX_StoryEpicRegionReferences_RegionId" 
    ON "alchimalia_schema"."StoryEpicRegionReferences" ("RegionId");

-- Create StoryEpicHeroReferences table (junction table)
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicHeroReferences" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EpicId" character varying(100) NOT NULL,
    "HeroId" character varying(100) NOT NULL,
    "StoryId" character varying(200),
    CONSTRAINT "PK_StoryEpicHeroReferences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicHeroReferences_StoryEpicDefinitions_EpicId" 
        FOREIGN KEY ("EpicId") REFERENCES "alchimalia_schema"."StoryEpicDefinitions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StoryEpicHeroReferences_EpicHeroes_HeroId" 
        FOREIGN KEY ("HeroId") REFERENCES "alchimalia_schema"."EpicHeroes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UQ_StoryEpicHeroReferences_EpicId_HeroId" 
        UNIQUE ("EpicId", "HeroId")
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicHeroReferences_EpicId" 
    ON "alchimalia_schema"."StoryEpicHeroReferences" ("EpicId");

CREATE INDEX IF NOT EXISTS "IX_StoryEpicHeroReferences_EpicId_HeroId" 
    ON "alchimalia_schema"."StoryEpicHeroReferences" ("EpicId", "HeroId");

CREATE INDEX IF NOT EXISTS "IX_StoryEpicHeroReferences_HeroId" 
    ON "alchimalia_schema"."StoryEpicHeroReferences" ("HeroId");

COMMIT;

