-- Adds StoryEpicCraftHeroReferences table for draft epics
-- Similar to StoryEpicCraftRegion - used for drafts, references StoryEpicCrafts instead of StoryEpics
-- Run date: 2025-12-15
-- Description: Adds hero references table for draft epics (StoryEpicCraft), matching the pattern used for regions

BEGIN;

-- Create StoryEpicCraftHeroReferences table (junction table for draft epics)
CREATE TABLE IF NOT EXISTS "alchimalia_schema"."StoryEpicCraftHeroReferences" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "EpicId" character varying(100) NOT NULL,
    "HeroId" character varying(100) NOT NULL,
    "StoryId" character varying(200),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
    CONSTRAINT "PK_StoryEpicCraftHeroReferences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StoryEpicCraftHeroReferences_StoryEpicCrafts_EpicId" 
        FOREIGN KEY ("EpicId") REFERENCES "alchimalia_schema"."StoryEpicCrafts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StoryEpicCraftHeroReferences_EpicHeroes_HeroId" 
        FOREIGN KEY ("HeroId") REFERENCES "alchimalia_schema"."EpicHeroes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "UQ_StoryEpicCraftHeroReferences_EpicId_HeroId" 
        UNIQUE ("EpicId", "HeroId")
);

CREATE INDEX IF NOT EXISTS "IX_StoryEpicCraftHeroReferences_EpicId" 
    ON "alchimalia_schema"."StoryEpicCraftHeroReferences" ("EpicId");
CREATE INDEX IF NOT EXISTS "IX_StoryEpicCraftHeroReferences_EpicId_HeroId" 
    ON "alchimalia_schema"."StoryEpicCraftHeroReferences" ("EpicId", "HeroId");
CREATE INDEX IF NOT EXISTS "IX_StoryEpicCraftHeroReferences_HeroId" 
    ON "alchimalia_schema"."StoryEpicCraftHeroReferences" ("HeroId");

COMMIT;

