namespace XooCreator.BA.Data.Entities;

/// <summary>LOI generative animal generated by a user (image + mini-story). One record per generation; 1 credit consumed.</summary>
public class UserGeneratedLoiAnimal
{
    public Guid Id { get; set; }
    public Guid UserId { get; set; }
    public AlchimaliaUser User { get; set; } = null!;

    /// <summary>Blob path (e.g. loi-generative/{userId}/{id}.png) or full URL. Used to resolve read URL in bestiary.</summary>
    public string ImageBlobPath { get; set; } = null!;
    public string StoryText { get; set; } = null!;
    /// <summary>JSON snapshot of parts/animal combination used for generation.</summary>
    public string? PartsSnapshotJson { get; set; }
    /// <summary>Display name for the generated creature (e.g. from combination or AI).</summary>
    public string Name { get; set; } = "Creature";
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
}
