# Nixpacks configuration for building a .NET 8 app on Railway without Docker

[phases.setup]
# Install only the .NET 8 SDK (includes the runtime) and native deps
# Installing both sdk and runtime causes file-collision errors in nix
nixPkgs = [
  "dotnet-sdk_8",
  "icu",
  "zlib",
  "openssl"
]

[phases.install]
# Restore NuGet packages - Railway sets root to XooCreator.BA directory
cmds = [
  "set -e",
  "echo \"Building from directory: $(pwd)\"",
  "echo \"Directory contents:\"",
  "ls -la",
  "echo \"Dotnet info (build stage):\"",
  "dotnet --info || true",
  "echo \"Restoring XooCreator.BA.csproj...\"",
  "dotnet restore XooCreator.BA.csproj --verbosity minimal"
]
cacheDirectories = ["/root/.nuget/packages"]

[phases.build]
# Compile and publish to a folder 'out' at the working directory
cmds = [
  "set -e",
  "echo \"Publishing project: XooCreator.BA.csproj\"",
  "dotnet publish XooCreator.BA.csproj -c Release -o ./out --no-restore --verbosity minimal",
  "echo \"Checking published files:\"",
  "ls -la ./out/",
  "echo \"Verifying XooCreator.BA.dll exists:\"",
  "test -f ./out/XooCreator.BA.dll && echo \"XooCreator.BA.dll found\" || (echo \"ERROR: XooCreator.BA.dll not found!\"; exit 1)"
]

[start]
# Remove global.json so runtime container (without SDK) doesn't print SDK resolution warning
cmd = """
echo \"Starting application from $(pwd)\"
# If running in a trimmed runtime image without SDK, global.json causes noisy warning, remove it safely
[ -f global.json ] && rm -f global.json || true
if [ -f ./out/XooCreator.BA.dll ]; then
  echo \"Running dotnet app...\>"
  exec dotnet ./out/XooCreator.BA.dll
else
  echo \"ERROR: ./out/XooCreator.BA.dll not found!\>"
  ls -la . || true
  ls -la ./out/ || echo \"Out directory missing\"
  exit 1
fi
"""

[variables]
# Bind to the port provided by Railway (also handled by Program.cs)
ASPNETCORE_URLS = "http://0.0.0.0:${PORT}"
# Use full globalization with ICU installed
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT = "false"
# Reduce noisy banners
DOTNET_CLI_TELEMETRY_OPTOUT = "true"
DOTNET_NOLOGO = "true"
