# Nixpacks configuration for building a .NET 8 app on Railway without Docker

[phases.setup]
# Install only the .NET 8 SDK (includes the runtime) and native deps
# Installing both sdk and runtime causes file-collision errors in nix
nixPkgs = [
  "dotnet-sdk_8",
  "icu",
  "zlib",
  "openssl"
]

[phases.install]
# Restore NuGet packages - Railway sets root to XooCreator.BA directory
cmds = [
  "set -e",
  "echo Building from directory: $(pwd)",
  "ls -la",
  "dotnet --info",
  "dotnet restore XooCreator.BA.csproj"
]
cacheDirectories = ["/root/.nuget/packages"]

[phases.build]
# Compile and publish to a folder 'out' at the working directory
cmds = [
  "set -e",
  "echo Publishing project: XooCreator.BA.csproj",
  "dotnet publish XooCreator.BA.csproj -c Release -o ./out"
]

[start]
# Start the published dll (works whether root is repo/ or /XooCreator.BA)
cmd = "dotnet ./out/XooCreator.BA.dll"

[variables]
# Bind to the port provided by Railway (also handled by Program.cs)
ASPNETCORE_URLS = "http://0.0.0.0:${PORT}"
# Use full globalization with ICU installed
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT = "false"
# Reduce noisy banners
DOTNET_CLI_TELEMETRY_OPTOUT = "true"
DOTNET_NOLOGO = "true"
