# Nixpacks configuration for building a .NET 8 app on Railway without Docker

[phases.setup]
# Install .NET 8 SDK + runtime and native deps
nixPkgs = [
  "dotnet-sdk_8",
  "dotnet-runtime_8",
  "icu",
  "zlib",
  "openssl"
]

[phases.install]
# Restore NuGet packages (auto-detect the csproj path)
cmds = [
  "set -e",
  "CSProj=$(find . -maxdepth 3 -name '*.csproj' | head -n 1)",
  "echo Using project: $CSProj",
  "dotnet restore \"$CSProj\""
]
cacheDirectories = ["/root/.nuget/packages"]

[phases.build]
# Compile and publish to a self-contained folder 'out'
cmds = [
  "set -e",
  "CSProj=$(find . -maxdepth 3 -name '*.csproj' | head -n 1)",
  "echo Publishing project: $CSProj",
  "dotnet publish \"$CSProj\" -c Release -o ./out"
]

[start]
# Use Procfile if present; otherwise start the published dll explicitly
cmd = "if [ -f Procfile ]; then ./.nixpacks/scripts/foreman Procfile; else dotnet ./out/XooCreator.BA.dll; fi"

[variables]
# Bind to the port provided by Railway (also handled by Program.cs)
ASPNETCORE_URLS = "http://0.0.0.0:${PORT}"
# Use full globalization with ICU installed
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT = "false"
