# Render Blueprint for XooCreator.BA (.NET 8 API)
# Docs: https://render.com/docs/infrastructure-as-code

services:
  - type: web
    name: xoo-creator-ba
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    buildContext: .
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: xoo-creator-postgres
          property: connectionString

# Managed PostgreSQL database; Render will expose its connection string.
databases:
  - name: xoo-creator-postgres
    plan: free
    databaseName: xoo_db
    user: xoo_user
